// taken directly from backend errors
// ERROR CODES
const UNEXPECTED_ERROR_CODE = "UNEXPECTED_ERROR";
const UNAUTHORIZED_ERROR_CODE = "UNAUTHORIZED_ERROR";
const BAD_REQUEST_ERROR_CODE = "BAD_REQUEST_ERROR";
const CONFLICT_ERROR_CODE = "RESOURCE_CONFLICT_ERROR";
const NOT_FOUND_ERROR_CODE = "NOT_FOUND_ERROR";